name: Repository Configurator
on: 
    repository_dispatch:
        types: [init-repo]
    workflow_dispatch:
      inputs:
        repo_name:
          description: 'A repo to sync the secrets.'
          required: false
jobs:
  configure-repo:
    runs-on: ubuntu-latest
    
  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository Settings Tool
        uses: actions/checkout@v1
        with:
          repository: mmravi99/DevopsBasics
          path: .DevopsBasics
          token: "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"        

      # Runs a set of commands using the runners shell
      - name: Run Repository Setting Configuration Tool
        run: |
           pip3 install pygithub
           python updaterepo.py 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 mmravi99/DevopsBasics
